// Code generated by "stringer -type=AutoSlot"; DO NOT EDIT.

package router

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AutoSlotInvalid - -1]
	_ = x[AutoSlotPrimary-0]
	_ = x[AutoSlotOverride-1]
}

const _AutoSlot_name = "AutoSlotInvalidAutoSlotPrimaryAutoSlotOverride"

var _AutoSlot_index = [...]uint8{0, 15, 30, 46}

func (i AutoSlot) String() string {
	i -= -1
	if i < 0 || i >= AutoSlot(len(_AutoSlot_index)-1) {
		return "AutoSlot(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _AutoSlot_name[_AutoSlot_index[i]:_AutoSlot_index[i+1]]
}
