// Code generated by "stringer -type=DualSlot"; DO NOT EDIT.

package router

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DualSlotSkip-0]
	_ = x[DualSlotA-1]
	_ = x[DualSlotB-2]
}

const _DualSlot_name = "DualSlotSkipDualSlotADualSlotB"

var _DualSlot_index = [...]uint8{0, 12, 21, 30}

func (i DualSlot) String() string {
	if i >= DualSlot(len(_DualSlot_index)-1) {
		return "DualSlot(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DualSlot_name[_DualSlot_index[i]:_DualSlot_index[i+1]]
}
