// Code generated by "stringer -type=TraceLevel -trimprefix=Level"; DO NOT EDIT.

package trace

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LevelTrace-0]
	_ = x[LevelDebug-1]
	_ = x[LevelInfo-2]
	_ = x[LevelWarn-3]
}

const _TraceLevel_name = "TraceDebugInfoWarn"

var _TraceLevel_index = [...]uint8{0, 5, 10, 14, 18}

func (i TraceLevel) String() string {
	if i < 0 || i >= TraceLevel(len(_TraceLevel_index)-1) {
		return "TraceLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TraceLevel_name[_TraceLevel_index[i]:_TraceLevel_index[i+1]]
}
