// Code generated by "stringer -type=Slot"; DO NOT EDIT.

package multi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SlotSkip-0]
	_ = x[SlotT-1]
	_ = x[SlotU-2]
	_ = x[SlotV-3]
}

const _Slot_name = "SlotSkipSlotTSlotUSlotV"

var _Slot_index = [...]uint8{0, 8, 13, 18, 23}

func (i Slot) String() string {
	if i >= Slot(len(_Slot_index)-1) {
		return "Slot(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Slot_name[_Slot_index[i]:_Slot_index[i+1]]
}
