// Code generated by "stringer -type=Slot"; DO NOT EDIT.

package auto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SlotInvalid - -1]
	_ = x[SlotPrimary-0]
	_ = x[SlotOverride-1]
}

const _Slot_name = "SlotInvalidSlotPrimarySlotOverride"

var _Slot_index = [...]uint8{0, 11, 22, 34}

func (i Slot) String() string {
	i -= -1
	if i < 0 || i >= Slot(len(_Slot_index)-1) {
		return "Slot(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _Slot_name[_Slot_index[i]:_Slot_index[i+1]]
}
